import {
  IMAGE_SCALE,
  canvasToPng,
  drawCircularImage,
  loadImage,
  roundRect,
  triggerFileDownload,
} from "@/lib/download-image";

export type HealthCardMember = {
  id: string;
  policy_number: string;
  full_name: string;
  relationship: string;
  dob: string;
  can_download: boolean;
  avatar: string;
};

const CARD_WIDTH = 640;
const CARD_HEIGHT = 400;

async function renderHealthCardPng(card: HealthCardMember): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = CARD_WIDTH * IMAGE_SCALE;
  canvas.height = CARD_HEIGHT * IMAGE_SCALE;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not create card image.");
  }

  ctx.scale(IMAGE_SCALE, IMAGE_SCALE);

  const background = ctx.createLinearGradient(0, 0, CARD_WIDTH, CARD_HEIGHT);
  background.addColorStop(0, "#FFF7ED");
  background.addColorStop(1, "#FFFFFF");

  roundRect(ctx, 0, 0, CARD_WIDTH, CARD_HEIGHT, 24);
  ctx.fillStyle = background;
  ctx.fill();
  ctx.strokeStyle = "#FED7AA";
  ctx.lineWidth = 2;
  ctx.stroke();

  roundRect(ctx, 0, 0, CARD_WIDTH, 72, 24);
  ctx.fillStyle = "#FF5E00";
  ctx.fill();
  ctx.fillRect(0, 48, CARD_WIDTH, 24);

  ctx.fillStyle = "#FFFFFF";
  ctx.font = "700 24px Arial, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText("Health Insurance Card", 32, 36);

  ctx.font = "600 18px Arial, sans-serif";
  ctx.textAlign = "right";
  ctx.fillText(`#${card.policy_number}`, CARD_WIDTH - 32, 36);

  const avatar = await loadImage(card.avatar);
  drawCircularImage(ctx, avatar, card.full_name, 40, 88, 72);

  ctx.fillStyle = "#111827";
  ctx.font = "700 28px Arial, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillText(card.full_name, 140, 118);

  ctx.fillStyle = "#6B7280";
  ctx.font = "500 18px Arial, sans-serif";
  ctx.fillText(`${card.relationship} · DOB ${card.dob}`, 140, 152);

  ctx.fillStyle = "#374151";
  ctx.font = "500 16px Arial, sans-serif";
  ctx.fillText("Policy No.", 140, 196);

  ctx.fillStyle = "#111827";
  ctx.font = "600 22px Arial, sans-serif";
  ctx.fillText(`#${card.policy_number}`, 140, 224);

  ctx.fillStyle = "#374151";
  ctx.font = "500 16px Arial, sans-serif";
  ctx.fillText(
    "Valid for cashless hospitalization subject to policy terms.",
    140,
    272,
  );

  ctx.fillStyle = "#9CA3AF";
  ctx.font = "500 14px Arial, sans-serif";
  ctx.fillText("Generated by Plans Insurance", 32, 360);

  return canvasToPng(canvas);
}

export async function downloadHealthCard(card: HealthCardMember): Promise<void> {
  if (!card.can_download) {
    throw new Error("This health card is not available for download.");
  }

  const png = await renderHealthCardPng(card);
  triggerFileDownload(png, `health-card-${card.policy_number}.png`);
}
