import {
  IMAGE_SCALE,
  canvasToPng,
  drawCircularImage,
  loadImage,
  roundRect,
  sanitizeFilename,
  triggerFileDownload,
} from "@/lib/download-image";

export type PolicyDetails = {
  policyId: string;
  type: string;
  status: string;
  provider: string;
  providerLogo: string;
  coverage: string;
  premium: string;
  claimAmount: string;
  members: Array<{ name: string; avatar: string }>;
  daysLeft: number;
  renewalDate: string;
  policyTerm: string;
};

const CARD_WIDTH = 900;
const CARD_HEIGHT = 280;

function drawDashedLine(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
) {
  ctx.save();
  ctx.strokeStyle = "#D1D5DB";
  ctx.lineWidth = 1;
  ctx.setLineDash([6, 6]);
  ctx.beginPath();
  ctx.moveTo(x, y);
  ctx.lineTo(x + width, y);
  ctx.stroke();
  ctx.restore();
}

function drawLabelValue(
  ctx: CanvasRenderingContext2D,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number,
) {
  ctx.fillStyle = "#6B7280";
  ctx.font = "500 14px Arial, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText(label, x, y, width);

  ctx.fillStyle = "#111827";
  ctx.font = "600 18px Arial, sans-serif";
  ctx.fillText(value, x, y + 22, width);
}

async function renderPolicyDetailsPng(policy: PolicyDetails): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = CARD_WIDTH * IMAGE_SCALE;
  canvas.height = CARD_HEIGHT * IMAGE_SCALE;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not create policy image.");
  }

  ctx.scale(IMAGE_SCALE, IMAGE_SCALE);

  const background = ctx.createLinearGradient(0, 0, 0, CARD_HEIGHT);
  background.addColorStop(0, "#F5F0FF");
  background.addColorStop(0.8, "#FFFFFF");

  roundRect(ctx, 0, 0, CARD_WIDTH, CARD_HEIGHT, 20);
  ctx.fillStyle = background;
  ctx.fill();
  ctx.strokeStyle = "#E5E7EB";
  ctx.lineWidth = 1;
  ctx.stroke();

  const logo = await loadImage(
    policy.providerLogo ||
      "https://img.freepik.com/free-vector/insurance-policy-shield_603843-179.jpg",
  );

  roundRect(ctx, 28, 28, 52, 52, 10);
  ctx.fillStyle = "#FFFFFF";
  ctx.fill();
  if (logo) {
    ctx.drawImage(logo, 32, 32, 44, 44);
  }

  ctx.fillStyle = "#111827";
  ctx.font = "700 28px Arial, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText(policy.provider, 92, 30);

  ctx.fillStyle = "#111827";
  ctx.font = "500 16px Arial, sans-serif";
  ctx.fillText(`${policy.type} · ${policy.policyId}`, 92, 68);

  ctx.fillStyle = "#6B7280";
  ctx.font = "500 14px Arial, sans-serif";
  ctx.fillText(`Status: ${policy.status} · Term: ${policy.policyTerm}`, 92, 92);

  drawDashedLine(ctx, 28, 124, CARD_WIDTH - 56);

  const columnWidth = (CARD_WIDTH - 56) / 5;
  const statsY = 148;
  drawLabelValue(
    ctx,
    "Coverage Amount",
    policy.coverage,
    28,
    statsY,
    columnWidth - 12,
  );
  drawLabelValue(
    ctx,
    "Premium",
    policy.premium,
    28 + columnWidth,
    statsY,
    columnWidth - 12,
  );
  drawLabelValue(
    ctx,
    "Claims Amt",
    policy.claimAmount,
    28 + columnWidth * 2,
    statsY,
    columnWidth - 12,
  );
  drawLabelValue(
    ctx,
    "Valid on",
    policy.renewalDate,
    28 + columnWidth * 3,
    statsY,
    columnWidth - 12,
  );

  ctx.fillStyle = "#6B7280";
  ctx.font = "500 14px Arial, sans-serif";
  ctx.fillText("Members", 28 + columnWidth * 4, statsY);

  const memberStartX = 28 + columnWidth * 4;
  const memberY = statsY + 24;
  const members = policy.members.slice(0, 3);

  if (members.length === 0) {
    ctx.fillStyle = "#111827";
    ctx.font = "600 18px Arial, sans-serif";
    ctx.fillText("None", memberStartX, memberY);
  } else {
    for (let index = 0; index < members.length; index += 1) {
      const member = members[index];
      const avatar = await loadImage(member.avatar);
      drawCircularImage(
        ctx,
        avatar,
        member.name,
        memberStartX + index * 34,
        memberY,
        32,
      );
    }
  }

  ctx.fillStyle = "#9CA3AF";
  ctx.font = "500 12px Arial, sans-serif";
  ctx.textAlign = "left";
  ctx.fillText("Generated by Plans Insurance", 28, CARD_HEIGHT - 24);

  return canvasToPng(canvas);
}

export async function downloadPolicyDetails(policy: PolicyDetails): Promise<void> {
  const png = await renderPolicyDetailsPng(policy);
  const filename = `policy-${sanitizeFilename(policy.policyId) || "details"}.png`;
  triggerFileDownload(png, filename);
}
